// packages/viostream-player-react/src/ViostreamPlayer.tsx
/**
 * ViostreamPlayer — React component that embeds a Viostream video player.
 *
 * @example
 * ```tsx
 * import { ViostreamPlayer } from '@viostream/viostream-player-react';
 * import type { ViostreamPlayerInstance } from '@viostream/viostream-player-react';
 *
 * function App() {
 *   const [player, setPlayer] = useState<ViostreamPlayerInstance>();
 *
 *   return (
 *     <ViostreamPlayer
 *       accountKey="vc-100100100"
 *       publicKey="nhedxonrxsyfee"
 *       displayTitle={true}
 *       sharing={true}
 *       onPlay={() => console.log('playing!')}
 *       onTimeUpdate={(d) => console.log('time:', d.seconds)}
 *       onPlayerReady={(p) => setPlayer(p)}
 *     />
 *   );
 * }
 * ```
 */

import { useEffect, useId, useRef, useState } from 'react';
import { loadViostream, wrapRawPlayer } from '@viostream/viostream-player-core';
import type {
  ViostreamEmbedOptions,
  ViostreamPlayer as ViostreamPlayerType,
  RawViostreamPlayerInstance,
  ViostreamEventHandler,
} from '@viostream/viostream-player-core';
import type { ViostreamPlayerProps } from './types.js';

// Maps React camelCase prop names → raw player event names
const EVENT_MAP: Array<[string, keyof ViostreamPlayerProps]> = [
  ['play', 'onPlay'],
  ['pause', 'onPause'],
  ['ended', 'onEnded'],
  ['timeupdate', 'onTimeUpdate'],
  ['volumechange', 'onVolumeChange'],
  ['error', 'onError'],
  ['progress', 'onProgress'],
  ['ready', 'onReady'],
  ['seeked', 'onSeeked'],
  ['loaded', 'onLoaded'],
];

export function ViostreamPlayer({
  // Required props
  accountKey,
  publicKey,

  // Embed options
  chapters,
  chapterSlug,
  displayTitle,
  hlsQualitySelector,
  playerKey,
  playerStyle,
  sharing,
  skinActive,
  skinBackground,
  skinCustom,
  skinInactive,
  speedSelector,
  startEndTimespan,
  startTime,
  transcriptDownload,
  useSettingsMenu,

  // Event callbacks
  onPlay,
  onPause,
  onEnded,
  onTimeUpdate,
  onVolumeChange,
  onError,
  onProgress,
  onReady,
  onSeeked,
  onLoaded,

  // Component callbacks
  onPlayerReady,

  // Render props
  renderLoading,
  renderError,

  // Styling
  className,
}: ViostreamPlayerProps): React.JSX.Element {
  const reactId = useId();
  const containerId = useRef(
    `viostream-player-${reactId.replace(/:/g, '').slice(0, 8)}${Math.random().toString(36).slice(2, 6)}`,
  );

  const [isLoading, setIsLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | undefined>();
  const playerRef = useRef<ViostreamPlayerType | undefined>(undefined);

  // Keep latest callback refs to avoid re-running the init effect when callbacks change
  const callbackRefs = useRef<Record<string, ViostreamEventHandler | undefined>>({});
  callbackRefs.current = {
    onPlay: onPlay as ViostreamEventHandler | undefined,
    onPause: onPause as ViostreamEventHandler | undefined,
    onEnded: onEnded as ViostreamEventHandler | undefined,
    onTimeUpdate: onTimeUpdate as ViostreamEventHandler | undefined,
    onVolumeChange: onVolumeChange as ViostreamEventHandler | undefined,
    onError: onError as ViostreamEventHandler | undefined,
    onProgress: onProgress as ViostreamEventHandler | undefined,
    onReady: onReady as ViostreamEventHandler | undefined,
    onSeeked: onSeeked as ViostreamEventHandler | undefined,
    onLoaded: onLoaded as ViostreamEventHandler | undefined,
  };
  const onPlayerReadyRef = useRef(onPlayerReady);
  onPlayerReadyRef.current = onPlayerReady;

  // Build the embed options object from props
  const embedOptsRef = useRef<ViostreamEmbedOptions>({});
  const embedOpts: ViostreamEmbedOptions = {};
  if (chapters !== undefined) embedOpts.chapters = chapters;
  if (chapterSlug !== undefined) embedOpts.chapterSlug = chapterSlug;
  if (displayTitle !== undefined) embedOpts.displayTitle = displayTitle;
  if (hlsQualitySelector !== undefined) embedOpts.hlsQualitySelector = hlsQualitySelector;
  if (playerKey !== undefined) embedOpts.playerKey = playerKey;
  if (playerStyle !== undefined) embedOpts.playerStyle = playerStyle;
  if (sharing !== undefined) embedOpts.sharing = sharing;
  if (skinActive !== undefined) embedOpts.skinActive = skinActive;
  if (skinBackground !== undefined) embedOpts.skinBackground = skinBackground;
  if (skinCustom !== undefined) embedOpts.skinCustom = skinCustom;
  if (skinInactive !== undefined) embedOpts.skinInactive = skinInactive;
  if (speedSelector !== undefined) embedOpts.speedSelector = speedSelector;
  if (startEndTimespan !== undefined) embedOpts.startEndTimespan = startEndTimespan;
  if (startTime !== undefined) embedOpts.startTime = startTime;
  if (transcriptDownload !== undefined) embedOpts.transcriptDownload = transcriptDownload;
  if (useSettingsMenu !== undefined) embedOpts.useSettingsMenu = useSettingsMenu;
  embedOptsRef.current = embedOpts;

  // -----------------------------------------------------------------------
  // Mount / unmount: load script, embed player, wire initial events
  // -----------------------------------------------------------------------
  useEffect(() => {
    let destroyed = false;

    async function init() {
      try {
        const api = await loadViostream(accountKey);

        if (destroyed) return;

        const raw: RawViostreamPlayerInstance = api.embed(
          publicKey,
          containerId.current,
          embedOptsRef.current,
        );
        const wrappedPlayer = wrapRawPlayer(raw, containerId.current);

        if (destroyed) {
          wrappedPlayer.destroy();
          return;
        }

        playerRef.current = wrappedPlayer;
        setIsLoading(false);

        // Notify consumer that the player is ready
        onPlayerReadyRef.current?.(wrappedPlayer);
      } catch (err) {
        if (!destroyed) {
          setErrorMsg(err instanceof Error ? err.message : String(err));
          setIsLoading(false);
        }
      }
    }

    init();

    return () => {
      destroyed = true;
      playerRef.current?.destroy();
      playerRef.current = undefined;
    };
    // Only re-init when accountKey or publicKey change
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accountKey, publicKey]);

  // -----------------------------------------------------------------------
  // Reactively re-wire event handlers when callback props change
  // -----------------------------------------------------------------------
  useEffect(() => {
    const player = playerRef.current;
    if (!player) return;

    const unsubscribers: Array<() => void> = [];

    for (const [eventName, propName] of EVENT_MAP) {
      const handler = callbackRefs.current[propName];
      if (handler) {
        const unsub = player.on(eventName, handler);
        unsubscribers.push(unsub);
      }
    }

    return () => {
      for (const unsub of unsubscribers) {
        unsub();
      }
    };
  }, [
    isLoading,
    onPlay,
    onPause,
    onEnded,
    onTimeUpdate,
    onVolumeChange,
    onError,
    onProgress,
    onReady,
    onSeeked,
    onLoaded,
  ]);

  return (
    <div
      id={containerId.current}
      className={className}
      data-viostream-player
      data-viostream-public-key={publicKey}
    >
      {isLoading && renderLoading ? renderLoading() : null}

      {errorMsg ? (
        renderError ? (
          renderError(errorMsg)
        ) : (
          <div data-viostream-error style={{ color: 'red', padding: '1em' }}>
            Failed to load Viostream player: {errorMsg}
          </div>
        )
      ) : null}
    </div>
  );
}

// packages/viostream-player-svelte/src/lib/ViostreamPlayer.svelte
<!--
  @component ViostreamPlayer

  Svelte 5 component that embeds a Viostream video player.

  Usage:
  ```svelte
  <script lang="ts">
    import { ViostreamPlayer } from '@viostream/viostream-player-svelte';
    import type { ViostreamPlayer as ViostreamPlayerType } from '@viostream/viostream-player-svelte';

    let player: ViostreamPlayerType | undefined = $state();
  </script>

  <ViostreamPlayer
    accountKey="vc-100100100"
    publicKey="nhedxonrxsyfee"
    displayTitle={true}
    sharing={true}
    onplay={() => console.log('playing!')}
    ontimeupdate={(d) => console.log('time:', d.seconds)}
    onplayerready={(p) => (player = p)}
  />
  ```
-->
<script lang="ts">
	import { onMount, type Snippet } from 'svelte';
	import { loadViostream, wrapRawPlayer } from '@viostream/viostream-player-core';
	import type {
		ViostreamEmbedOptions,
		ViostreamPlayer,
		RawViostreamPlayerInstance,
		ViostreamEventHandler,
	} from '@viostream/viostream-player-core';
	import type { ViostreamPlayerProps } from './types.js';

	let {
		// Required props
		accountKey,
		publicKey,

		// Embed options
		chapters,
		chapterSlug,
		displayTitle,
		hlsQualitySelector,
		playerKey,
		playerStyle,
		sharing,
		skinActive,
		skinBackground,
		skinCustom,
		skinInactive,
		speedSelector,
		startEndTimespan,
		startTime,
		transcriptDownload,
		useSettingsMenu,

		// Event callbacks
		onplay,
		onpause,
		onended,
		ontimeupdate,
		onvolumechange,
		onerror,
		onprogress,
		onready,
		onseeked,
		onloaded,

		// Component callbacks
		onplayerready,

		// Snippet overrides
		loading: loadingSnippet,
		error: errorSnippet,

		// Styling
		class: className,

		// Spread rest for future-proofing
		...restProps
	}: ViostreamPlayerProps & {
		loading?: Snippet;
		error?: Snippet<[string]>;
	} = $props();

	// Internal state
	let containerEl: HTMLDivElement | undefined = $state();
	let player: ViostreamPlayer | undefined = $state();
	let errorMsg: string | undefined = $state();
	let isLoading = $state(true);

	// Unique ID for the container
	const containerId = `viostream-player-${Math.random().toString(36).slice(2, 10)}`;

	// Build the embed options object from props
	function buildEmbedOptions(): ViostreamEmbedOptions {
		const opts: ViostreamEmbedOptions = {};
		if (chapters !== undefined) opts.chapters = chapters;
		if (chapterSlug !== undefined) opts.chapterSlug = chapterSlug;
		if (displayTitle !== undefined) opts.displayTitle = displayTitle;
		if (hlsQualitySelector !== undefined) opts.hlsQualitySelector = hlsQualitySelector;
		if (playerKey !== undefined) opts.playerKey = playerKey;
		if (playerStyle !== undefined) opts.playerStyle = playerStyle;
		if (sharing !== undefined) opts.sharing = sharing;
		if (skinActive !== undefined) opts.skinActive = skinActive;
		if (skinBackground !== undefined) opts.skinBackground = skinBackground;
		if (skinCustom !== undefined) opts.skinCustom = skinCustom;
		if (skinInactive !== undefined) opts.skinInactive = skinInactive;
		if (speedSelector !== undefined) opts.speedSelector = speedSelector;
		if (startEndTimespan !== undefined) opts.startEndTimespan = startEndTimespan;
		if (startTime !== undefined) opts.startTime = startTime;
		if (transcriptDownload !== undefined) opts.transcriptDownload = transcriptDownload;
		if (useSettingsMenu !== undefined) opts.useSettingsMenu = useSettingsMenu;
		return opts;
	}

	// Event wiring: maps event names to their prop callbacks
	const EVENT_MAP: Array<[string, (() => ViostreamEventHandler | undefined)]> = [
		['play', () => onplay as ViostreamEventHandler | undefined],
		['pause', () => onpause as ViostreamEventHandler | undefined],
		['ended', () => onended as ViostreamEventHandler | undefined],
		['timeupdate', () => ontimeupdate as ViostreamEventHandler | undefined],
		['volumechange', () => onvolumechange as ViostreamEventHandler | undefined],
		['error', () => onerror as ViostreamEventHandler | undefined],
		['progress', () => onprogress as ViostreamEventHandler | undefined],
		['ready', () => onready as ViostreamEventHandler | undefined],
		['seeked', () => onseeked as ViostreamEventHandler | undefined],
		['loaded', () => onloaded as ViostreamEventHandler | undefined]
	];

	onMount(() => {
		let destroyed = false;
		const unsubscribers: Array<() => void> = [];

		async function init() {
			try {
				const api = await loadViostream(accountKey);

				if (destroyed) return;

				const embedOpts = buildEmbedOptions();
				const raw: RawViostreamPlayerInstance = api.embed(publicKey, containerId, embedOpts);
				const wrappedPlayer = wrapRawPlayer(raw, containerId);

				if (destroyed) {
					wrappedPlayer.destroy();
					return;
				}

				player = wrappedPlayer;
				isLoading = false;

				// Wire up event callbacks from props
				for (const [eventName, getHandler] of EVENT_MAP) {
					const handler = getHandler();
					if (handler) {
						const unsub = wrappedPlayer.on(eventName, handler);
						unsubscribers.push(unsub);
					}
				}

				// Notify consumer that the player is ready
				onplayerready?.(wrappedPlayer);
			} catch (err) {
				if (!destroyed) {
					errorMsg = err instanceof Error ? err.message : String(err);
					isLoading = false;
				}
			}
		}

		init();

		return () => {
			destroyed = true;
			for (const unsub of unsubscribers) {
				unsub();
			}
			player?.destroy();
			player = undefined;
		};
	});

	// Re-wire event handlers reactively when callback props change
	// This handles the case where a consumer conditionally provides callbacks
	$effect(() => {
		if (!player) return;

		const currentUnsubscribers: Array<() => void> = [];

		for (const [eventName, getHandler] of EVENT_MAP) {
			const handler = getHandler();
			if (handler) {
				const unsub = player.on(eventName, handler);
				currentUnsubscribers.push(unsub);
			}
		}

		return () => {
			for (const unsub of currentUnsubscribers) {
				unsub();
			}
		};
	});
</script>

<div
	id={containerId}
	class={className}
	bind:this={containerEl}
	data-viostream-player
	data-viostream-public-key={publicKey}
>
	{#if isLoading}
		{#if loadingSnippet}
			{@render loadingSnippet()}
		{/if}
	{/if}

	{#if errorMsg}
		{#if errorSnippet}
			{@render errorSnippet(errorMsg)}
		{:else}
			<div data-viostream-error style="color: red; padding: 1em;">
				Failed to load Viostream player: {errorMsg}
			</div>
		{/if}
	{/if}
</div>
