// packages/viostream-player-angular/src/viostream-player.component.ts
/**
 * ViostreamPlayerComponent — Angular standalone component that embeds a Viostream video player.
 *
 * @example
 * ```html
 * <viostream-player
 *   [accountKey]="'vc-100100100'"
 *   [publicKey]="'nhedxonrxsyfee'"
 *   [displayTitle]="true"
 *   [sharing]="true"
 *   (play)="onPlay()"
 *   (timeUpdate)="onTimeUpdate($event)"
 *   (playerReady)="onPlayerReady($event)"
 * />
 * ```
 */

import {
  Component,
  Input,
  OnInit,
  OnDestroy,
  ElementRef,
  NgZone,
  inject,
  output,
  signal,
  viewChild,
} from '@angular/core';
import Debug from 'debug';
import { getViostreamApi, wrapRawPlayer, normalizeForceAspectRatio } from '@viostream/viostream-player-core';
import type {
  ViostreamEmbedOptions,
  ViostreamPlayer,
  RawViostreamPlayerInstance,
  ViostreamEventHandler,
  ViostreamTimeUpdateData,
  ViostreamVolumeChangeData,
  ViostreamErrorData,
  ViostreamProgressData,
} from '@viostream/viostream-player-core';
import { SDK_NAME, SDK_VERSION } from './version';

const debug = Debug('viostream:angular');

@Component({
  selector: 'viostream-player',
  standalone: true,
  template: `
    <div
      #container
      [id]="containerId"
      [class]="cssClass"
      data-viostream-player
      [attr.data-viostream-public-key]="publicKey"
      [attr.data-viostream-sdk]="sdkTag"
    >
      @if (isLoading()) {
        <ng-content select="[loading]" />
      }

      @if (errorMsg(); as msg) {
        <div data-viostream-error style="color: red; padding: 1em;">
          Failed to load Viostream player: {{ msg }}
        </div>
      }
    </div>
  `,
})
export class ViostreamPlayerComponent implements OnInit, OnDestroy {
  // ---------------------------------------------------------------------------
  // Inputs (required)
  // ---------------------------------------------------------------------------

  /** Your Viostream account key (e.g. `'vc-100100100'`). */
  @Input({ required: true }) accountKey!: string;
  /** The public key of the media asset to embed. */
  @Input({ required: true }) publicKey!: string;

  // ---------------------------------------------------------------------------
  // Inputs (embed options)
  // ---------------------------------------------------------------------------

  /** Display chapter markers. */
  @Input() chapters?: boolean;
  /** Seek to a named chapter before playback begins. */
  @Input() chapterSlug?: string;
  /** Show the video title overlay. */
  @Input() displayTitle?: boolean;
  /** Show the HLS quality selector control. */
  @Input() hlsQualitySelector?: boolean;
  /** Override the player theme/key to use. */
  @Input() playerKey?: string;
  /** The player rendering style. */
  @Input() playerStyle?: 'video' | 'audio' | 'audio-poster';
  /** Show the sharing control. */
  @Input() sharing?: boolean;
  /** Custom skin active colour (e.g. `'#000'`). Requires `skinCustom: true`. */
  @Input() skinActive?: string;
  /** Custom skin background colour (e.g. `'#000'`). Requires `skinCustom: true`. */
  @Input() skinBackground?: string;
  /** Enable a custom skin via the API. */
  @Input() skinCustom?: boolean;
  /** Custom skin inactive colour (e.g. `'#000'`). Requires `skinCustom: true`. */
  @Input() skinInactive?: string;
  /** Show the playback speed selector. */
  @Input() speedSelector?: boolean;
  /** Play only a specific section of the video (e.g. `'10,30'`). */
  @Input() startEndTimespan?: string;
  /** Seek to a specific time (in seconds) before playback begins. */
  @Input() startTime?: string;
  /** Allow transcript download. */
  @Input() transcriptDownload?: boolean;
  /** Enable the settings menu on the control bar. */
  @Input() useSettingsMenu?: boolean;
  /** Force a specific aspect ratio for the player container (e.g., `1.7778` for 16:9). */
  @Input() forceAspectRatio?: number;

  // ---------------------------------------------------------------------------
  // Inputs (styling)
  // ---------------------------------------------------------------------------

  /** Optional CSS class applied to the outer wrapper `<div>`. */
  @Input() cssClass?: string;

  // ---------------------------------------------------------------------------
  // Outputs (player events)
  // ---------------------------------------------------------------------------

  /** Emitted when playback starts or resumes. */
  readonly play = output<void>();
  /** Emitted when playback is paused. */
  readonly pause = output<void>();
  /** Emitted when the media finishes playing. */
  readonly ended = output<void>();
  /** Emitted when the current playback time changes. */
  readonly timeUpdate = output<ViostreamTimeUpdateData>();
  /** Emitted when the volume changes. */
  readonly volumeChange = output<ViostreamVolumeChangeData>();
  /** Emitted when a player error occurs. Named `playerError` to avoid conflict with the native DOM `error` event. */
  readonly playerError = output<ViostreamErrorData>();
  /** Emitted on buffering progress. */
  readonly progress = output<ViostreamProgressData>();
  /** Emitted when the player is ready. */
  readonly ready = output<void>();
  /** Emitted when a seek operation completes. */
  readonly seeked = output<void>();
  /** Emitted when metadata has loaded. */
  readonly loaded = output<void>();
  /** Emitted once the player is ready, providing the `ViostreamPlayer` instance for programmatic control. */
  readonly playerReady = output<ViostreamPlayer>();

  // ---------------------------------------------------------------------------
  // Internal state
  // ---------------------------------------------------------------------------

  /** Unique ID for the player container element. */
  readonly containerId = `viostream-player-${Math.random().toString(36).slice(2, 10)}`;

  /** SDK identifier stamped as a data attribute on the container. */
  readonly sdkTag = `${SDK_NAME}@${SDK_VERSION}`;

  /** Whether the player is still loading. */
  readonly isLoading = signal(true);

  /** Error message if loading failed. */
  readonly errorMsg = signal<string | undefined>(undefined);

  /** Reference to the container div. */
  private readonly containerRef = viewChild<ElementRef<HTMLDivElement>>('container');

  /** The wrapped player instance. */
  private player: ViostreamPlayer | undefined;

  /** Whether the component has been destroyed. */
  private destroyed = false;

  /** Unsubscribe functions for event listeners. */
  private readonly unsubscribers: Array<() => void> = [];

  /** Angular zone for triggering change detection. */
  private readonly ngZone = inject(NgZone);

  // ---------------------------------------------------------------------------
  // Lifecycle
  // ---------------------------------------------------------------------------

  ngOnInit(): void {
    debug('ngOnInit publicKey=%s accountKey=%s containerId=%s', this.publicKey, this.accountKey, this.containerId);
    this.init();
  }

  ngOnDestroy(): void {
    debug('ngOnDestroy publicKey=%s hasPlayer=%s', this.publicKey, !!this.player);
    this.destroyed = true;
    this.unwireEvents();
    this.player?.destroy();
    this.player = undefined;
  }

  // ---------------------------------------------------------------------------
  // Private methods
  // ---------------------------------------------------------------------------

  private async init(): Promise<void> {
    try {
      debug('init: getting embed API');
      const api = getViostreamApi();

      if (this.destroyed) {
        debug('init: destroyed detected after getViostreamApi — aborting publicKey=%s', this.publicKey);
        return;
      }

      const embedOpts = this.buildEmbedOptions();
      debug('init: calling api.embed publicKey=%s containerId=%s options=%o', this.publicKey, this.containerId, embedOpts);
      const raw: RawViostreamPlayerInstance = api.embed(
        this.publicKey,
        this.containerId,
        embedOpts,
        embedOpts.forceAspectRatio,
      );
      debug('init: api.embed returned raw player');

      const wrappedPlayer = wrapRawPlayer(raw, this.containerId);
      debug('init: wrapRawPlayer completed containerId=%s', this.containerId);

      if (this.destroyed) {
        debug('init: destroyed detected after wrapRawPlayer — destroying and aborting publicKey=%s', this.publicKey);
        wrappedPlayer.destroy();
        return;
      }

      this.player = wrappedPlayer;

      // Run state updates inside NgZone to trigger change detection
      this.ngZone.run(() => {
        this.isLoading.set(false);
      });
      debug('init: player set, isLoading -> false publicKey=%s', this.publicKey);

      // Wire up event callbacks
      this.wireEvents(wrappedPlayer);

      // Notify consumer that the player is ready
      debug('init: emitting playerReady publicKey=%s', this.publicKey);
      this.playerReady.emit(wrappedPlayer);
    } catch (err) {
      if (!this.destroyed) {
        const msg = err instanceof Error ? err.message : String(err);
        debug('init: error caught publicKey=%s error=%s', this.publicKey, msg);
        this.ngZone.run(() => {
          this.errorMsg.set(msg);
          this.isLoading.set(false);
        });
      } else {
        debug('init: error caught but destroyed — ignoring publicKey=%s', this.publicKey);
      }
    }
  }

  private buildEmbedOptions(): ViostreamEmbedOptions {
    const opts: ViostreamEmbedOptions = {};
    if (this.chapters !== undefined) opts.chapters = this.chapters;
    if (this.chapterSlug !== undefined) opts.chapterSlug = this.chapterSlug;
    if (this.displayTitle !== undefined) opts.displayTitle = this.displayTitle;
    if (this.hlsQualitySelector !== undefined) opts.hlsQualitySelector = this.hlsQualitySelector;
    if (this.playerKey !== undefined) opts.playerKey = this.playerKey;
    if (this.playerStyle !== undefined) opts.playerStyle = this.playerStyle;
    if (this.sharing !== undefined) opts.sharing = this.sharing;
    if (this.skinActive !== undefined) opts.skinActive = this.skinActive;
    if (this.skinBackground !== undefined) opts.skinBackground = this.skinBackground;
    if (this.skinCustom !== undefined) opts.skinCustom = this.skinCustom;
    if (this.skinInactive !== undefined) opts.skinInactive = this.skinInactive;
    if (this.speedSelector !== undefined) opts.speedSelector = this.speedSelector;
    if (this.startEndTimespan !== undefined) opts.startEndTimespan = this.startEndTimespan;
    if (this.startTime !== undefined) opts.startTime = this.startTime;
    if (this.transcriptDownload !== undefined) opts.transcriptDownload = this.transcriptDownload;
    if (this.useSettingsMenu !== undefined) opts.useSettingsMenu = this.useSettingsMenu;
    if (this.forceAspectRatio !== undefined) opts.forceAspectRatio = normalizeForceAspectRatio(this.forceAspectRatio);
    return opts;
  }

  /** Maps raw player event names to component output emitters. */
  private readonly EVENT_MAP: Array<[string, ViostreamEventHandler]> = [
    ['play', () => this.ngZone.run(() => this.play.emit())],
    ['pause', () => this.ngZone.run(() => this.pause.emit())],
    ['ended', () => this.ngZone.run(() => this.ended.emit())],
    ['timeupdate', (data: unknown) => this.ngZone.run(() => this.timeUpdate.emit(data as ViostreamTimeUpdateData))],
    ['volumechange', (data: unknown) => this.ngZone.run(() => this.volumeChange.emit(data as ViostreamVolumeChangeData))],
    ['error', (data: unknown) => this.ngZone.run(() => this.playerError.emit(data as ViostreamErrorData))],
    ['progress', (data: unknown) => this.ngZone.run(() => this.progress.emit(data as ViostreamProgressData))],
    ['ready', () => this.ngZone.run(() => this.ready.emit())],
    ['seeked', () => this.ngZone.run(() => this.seeked.emit())],
    ['loaded', () => this.ngZone.run(() => this.loaded.emit())],
  ];

  private wireEvents(wrappedPlayer: ViostreamPlayer): void {
    const wiredEvents: string[] = [];
    for (const [eventName, handler] of this.EVENT_MAP) {
      const unsub = wrappedPlayer.on(eventName, handler);
      this.unsubscribers.push(unsub);
      wiredEvents.push(eventName);
    }
    debug('wireEvents: subscribed to [%s]', wiredEvents.join(', '));
  }

  private unwireEvents(): void {
    debug('unwireEvents: unsubscribing %d events', this.unsubscribers.length);
    for (const unsub of this.unsubscribers) {
      unsub();
    }
    this.unsubscribers.length = 0;
  }
}

// packages/viostream-player-vue/src/ViostreamPlayer.vue
<!--
  ViostreamPlayer — Vue 3 component that embeds a Viostream video player.

  Usage:
    import { ViostreamPlayer } from '@viostream/viostream-player-vue';
-->

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import Debug from 'debug';
import { getViostreamApi, wrapRawPlayer, normalizeForceAspectRatio } from '@viostream/viostream-player-core';
import type {
  ViostreamEmbedOptions,
  ViostreamPlayer,
  RawViostreamPlayerInstance,
  ViostreamEventHandler,
  ViostreamTimeUpdateData,
  ViostreamVolumeChangeData,
  ViostreamErrorData,
  ViostreamProgressData,
} from '@viostream/viostream-player-core';
import { SDK_NAME, SDK_VERSION } from './version.js';

const debug = Debug('viostream:vue');

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = withDefaults(defineProps<{
  // Required props
  accountKey: string;
  publicKey: string;

  // Embed options
  chapters?: boolean;
  chapterSlug?: string;
  displayTitle?: boolean;
  hlsQualitySelector?: boolean;
  playerKey?: string;
  playerStyle?: 'video' | 'audio' | 'audio-poster';
  sharing?: boolean;
  skinActive?: string;
  skinBackground?: string;
  skinCustom?: boolean;
  skinInactive?: string;
  speedSelector?: boolean;
  startEndTimespan?: string;
  startTime?: string;
  transcriptDownload?: boolean;
  useSettingsMenu?: boolean;
  forceAspectRatio?: number;

  // Styling
  class?: string;
}>(), {
  chapters: undefined,
  chapterSlug: undefined,
  displayTitle: undefined,
  hlsQualitySelector: undefined,
  playerKey: undefined,
  playerStyle: undefined,
  sharing: undefined,
  skinActive: undefined,
  skinBackground: undefined,
  skinCustom: undefined,
  skinInactive: undefined,
  speedSelector: undefined,
  startEndTimespan: undefined,
  startTime: undefined,
  transcriptDownload: undefined,
  useSettingsMenu: undefined,
  forceAspectRatio: undefined,
  class: undefined,
});

// ---------------------------------------------------------------------------
// Emits
// ---------------------------------------------------------------------------

const emit = defineEmits<{
  play: [];
  pause: [];
  ended: [];
  timeUpdate: [data: ViostreamTimeUpdateData];
  volumeChange: [data: ViostreamVolumeChangeData];
  error: [data: ViostreamErrorData];
  progress: [data: ViostreamProgressData];
  ready: [];
  seeked: [];
  loaded: [];
  playerReady: [player: ViostreamPlayer];
}>();

// ---------------------------------------------------------------------------
// Slots
// ---------------------------------------------------------------------------

defineSlots<{
  loading?: () => unknown;
  error?: (props: { message: string }) => unknown;
}>();

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

const containerId = `viostream-player-${Math.random().toString(36).slice(2, 10)}`;
const containerRef = ref<HTMLDivElement>();
const player = ref<ViostreamPlayer>();
const errorMsg = ref<string>();
const isLoading = ref(true);

let destroyed = false;
const unsubscribers: Array<() => void> = [];

debug('component setup publicKey=%s containerId=%s', props.publicKey, containerId);

// ---------------------------------------------------------------------------
// Build embed options from props
// ---------------------------------------------------------------------------

function buildEmbedOptions(): ViostreamEmbedOptions {
  const opts: ViostreamEmbedOptions = {};
  if (props.chapters !== undefined) opts.chapters = props.chapters;
  if (props.chapterSlug !== undefined) opts.chapterSlug = props.chapterSlug;
  if (props.displayTitle !== undefined) opts.displayTitle = props.displayTitle;
  if (props.hlsQualitySelector !== undefined) opts.hlsQualitySelector = props.hlsQualitySelector;
  if (props.playerKey !== undefined) opts.playerKey = props.playerKey;
  if (props.playerStyle !== undefined) opts.playerStyle = props.playerStyle;
  if (props.sharing !== undefined) opts.sharing = props.sharing;
  if (props.skinActive !== undefined) opts.skinActive = props.skinActive;
  if (props.skinBackground !== undefined) opts.skinBackground = props.skinBackground;
  if (props.skinCustom !== undefined) opts.skinCustom = props.skinCustom;
  if (props.skinInactive !== undefined) opts.skinInactive = props.skinInactive;
  if (props.speedSelector !== undefined) opts.speedSelector = props.speedSelector;
  if (props.startEndTimespan !== undefined) opts.startEndTimespan = props.startEndTimespan;
  if (props.startTime !== undefined) opts.startTime = props.startTime;
  if (props.transcriptDownload !== undefined) opts.transcriptDownload = props.transcriptDownload;
  if (props.useSettingsMenu !== undefined) opts.useSettingsMenu = props.useSettingsMenu;
  return opts;
}

// ---------------------------------------------------------------------------
// Event wiring
// ---------------------------------------------------------------------------

const EVENT_MAP: Array<[string, (...args: never[]) => void]> = [
  ['play', () => emit('play')],
  ['pause', () => emit('pause')],
  ['ended', () => emit('ended')],
  ['timeUpdate', (data: ViostreamTimeUpdateData) => emit('timeUpdate', data)],
  ['volumeChange', (data: ViostreamVolumeChangeData) => emit('volumeChange', data)],
  ['error', (data: ViostreamErrorData) => emit('error', data)],
  ['progress', (data: ViostreamProgressData) => emit('progress', data)],
  ['ready', () => emit('ready')],
  ['seeked', () => emit('seeked')],
  ['loaded', () => emit('loaded')],
];

// Maps emit event names to raw player event names
const RAW_EVENT_MAP: Record<string, string> = {
  play: 'play',
  pause: 'pause',
  ended: 'ended',
  timeUpdate: 'timeupdate',
  volumeChange: 'volumechange',
  error: 'error',
  progress: 'progress',
  ready: 'ready',
  seeked: 'seeked',
  loaded: 'loaded',
};

function wireEvents(wrappedPlayer: ViostreamPlayer): void {
  const wiredEvents: string[] = [];
  for (const [emitName, handler] of EVENT_MAP) {
    const rawName = RAW_EVENT_MAP[emitName];
    if (rawName) {
      const unsub = wrappedPlayer.on(rawName, handler as ViostreamEventHandler);
      unsubscribers.push(unsub);
      wiredEvents.push(rawName);
    }
  }
  debug('wireEvents: subscribed to [%s]', wiredEvents.join(', '));
}

function unwireEvents(): void {
  debug('unwireEvents: unsubscribing %d events', unsubscribers.length);
  for (const unsub of unsubscribers) {
    unsub();
  }
  unsubscribers.length = 0;
}

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------

async function init(): Promise<void> {
  try {
    debug('init: getting embed API');
    const api = getViostreamApi();

    if (destroyed) {
      debug('init: stale closure detected after getViostreamApi — aborting publicKey=%s', props.publicKey);
      return;
    }

    const embedOpts = buildEmbedOptions();
    debug('init: calling api.embed publicKey=%s containerId=%s options=%o', props.publicKey, containerId, embedOpts);
    const raw: RawViostreamPlayerInstance = api.embed(props.publicKey, containerId, embedOpts, normalizeForceAspectRatio(props.forceAspectRatio));
    debug('init: api.embed returned raw player');

    const wrappedPlayer = wrapRawPlayer(raw, containerId);
    debug('init: wrapRawPlayer completed containerId=%s', containerId);

    if (destroyed) {
      debug('init: stale closure detected after wrapRawPlayer — destroying and aborting publicKey=%s', props.publicKey);
      wrappedPlayer.destroy();
      return;
    }

    player.value = wrappedPlayer;
    isLoading.value = false;
    debug('init: player set, isLoading -> false publicKey=%s', props.publicKey);

    // Wire up event callbacks
    wireEvents(wrappedPlayer);

    // Notify consumer that the player is ready
    debug('init: emitting playerReady publicKey=%s', props.publicKey);
    emit('playerReady', wrappedPlayer);
  } catch (err) {
    if (!destroyed) {
      const msg = err instanceof Error ? err.message : String(err);
      debug('init: error caught publicKey=%s error=%s', props.publicKey, msg);
      errorMsg.value = msg;
      isLoading.value = false;
    } else {
      debug('init: error caught but destroyed — ignoring publicKey=%s', props.publicKey);
    }
  }
}

onMounted(() => {
  debug('onMounted publicKey=%s accountKey=%s containerId=%s', props.publicKey, props.accountKey, containerId);
  init();
});

onUnmounted(() => {
  debug('onUnmounted publicKey=%s hasPlayer=%s', props.publicKey, !!player.value);
  destroyed = true;
  unwireEvents();
  player.value?.destroy();
  player.value = undefined;
});
</script>

<template>
  <div
    :id="containerId"
    :class="props.class"
    ref="containerRef"
    data-viostream-player
    :data-viostream-public-key="publicKey"
    :data-viostream-sdk="`${SDK_NAME}@${SDK_VERSION}`"
  >
    <slot v-if="isLoading" name="loading" />

    <template v-if="errorMsg">
      <slot name="error" :message="errorMsg">
        <div data-viostream-error style="color: red; padding: 1em;">
          Failed to load Viostream player: {{ errorMsg }}
        </div>
      </slot>
    </template>
  </div>
</template>
